// This file is generated by scripts/generate-model-types.mjs. Do not edit.
// Descriptor declarations are generated by @bpmn-io/moddle-types-generator.

import type { ModdleElement } from "moddle";
import type { BpmnModdleTypeMap } from "./model-types.generated/bpmn.js";
import type { BpmndiModdleTypeMap } from "./model-types.generated/bpmndi.js";
import type { DcModdleTypeMap } from "./model-types.generated/dc.js";
import type { DiModdleTypeMap } from "./model-types.generated/di.js";
import type { ZeebeModdleTypeMap } from "./model-types.generated/zeebe.js";

import type { ZeebeBindingTypeSupported } from "./model-types.generated/zeebe.js";
import type { ZeebeConfigurationSupported } from "./model-types.generated/zeebe.js";
import type { ZeebeTemplatedRootElement } from "./model-types.generated/zeebe.js";
import type { ZeebeTemplateSupported } from "./model-types.generated/zeebe.js";
import type { ZeebeZeebeServiceTask } from "./model-types.generated/zeebe.js";

export interface ModdleTypeMap extends BpmnModdleTypeMap, BpmndiModdleTypeMap, DcModdleTypeMap, DiModdleTypeMap, ZeebeModdleTypeMap {}

type ConstructibleModdleTypeMap = Pick<ModdleTypeMap,
  | "bpmn:AdHocSubProcess"
  | "bpmn:Assignment"
  | "bpmn:Association"
  | "bpmn:Auditing"
  | "bpmn:BoundaryEvent"
  | "bpmn:BusinessRuleTask"
  | "bpmn:CallActivity"
  | "bpmn:CallChoreography"
  | "bpmn:CallConversation"
  | "bpmn:CancelEventDefinition"
  | "bpmn:Category"
  | "bpmn:CategoryValue"
  | "bpmn:Choreography"
  | "bpmn:ChoreographyTask"
  | "bpmn:Collaboration"
  | "bpmn:CompensateEventDefinition"
  | "bpmn:ComplexBehaviorDefinition"
  | "bpmn:ComplexGateway"
  | "bpmn:ConditionalEventDefinition"
  | "bpmn:Conversation"
  | "bpmn:ConversationAssociation"
  | "bpmn:ConversationLink"
  | "bpmn:CorrelationKey"
  | "bpmn:CorrelationProperty"
  | "bpmn:CorrelationPropertyBinding"
  | "bpmn:CorrelationPropertyRetrievalExpression"
  | "bpmn:CorrelationSubscription"
  | "bpmn:DataAssociation"
  | "bpmn:DataInput"
  | "bpmn:DataInputAssociation"
  | "bpmn:DataObject"
  | "bpmn:DataObjectReference"
  | "bpmn:DataOutput"
  | "bpmn:DataOutputAssociation"
  | "bpmn:DataState"
  | "bpmn:DataStore"
  | "bpmn:DataStoreReference"
  | "bpmn:Definitions"
  | "bpmn:Documentation"
  | "bpmn:EndEvent"
  | "bpmn:EndPoint"
  | "bpmn:Error"
  | "bpmn:ErrorEventDefinition"
  | "bpmn:Escalation"
  | "bpmn:EscalationEventDefinition"
  | "bpmn:EventBasedGateway"
  | "bpmn:ExclusiveGateway"
  | "bpmn:Expression"
  | "bpmn:Extension"
  | "bpmn:ExtensionAttributeDefinition"
  | "bpmn:ExtensionDefinition"
  | "bpmn:ExtensionElements"
  | "bpmn:FormalExpression"
  | "bpmn:GlobalBusinessRuleTask"
  | "bpmn:GlobalChoreographyTask"
  | "bpmn:GlobalConversation"
  | "bpmn:GlobalManualTask"
  | "bpmn:GlobalScriptTask"
  | "bpmn:GlobalTask"
  | "bpmn:GlobalUserTask"
  | "bpmn:Group"
  | "bpmn:HumanPerformer"
  | "bpmn:ImplicitThrowEvent"
  | "bpmn:Import"
  | "bpmn:InclusiveGateway"
  | "bpmn:InputOutputBinding"
  | "bpmn:InputOutputSpecification"
  | "bpmn:InputSet"
  | "bpmn:Interface"
  | "bpmn:IntermediateCatchEvent"
  | "bpmn:IntermediateThrowEvent"
  | "bpmn:ItemAwareElement"
  | "bpmn:ItemDefinition"
  | "bpmn:Lane"
  | "bpmn:LaneSet"
  | "bpmn:LinkEventDefinition"
  | "bpmn:ManualTask"
  | "bpmn:Message"
  | "bpmn:MessageEventDefinition"
  | "bpmn:MessageFlow"
  | "bpmn:MessageFlowAssociation"
  | "bpmn:Monitoring"
  | "bpmn:MultiInstanceLoopCharacteristics"
  | "bpmn:Operation"
  | "bpmn:OutputSet"
  | "bpmn:ParallelGateway"
  | "bpmn:Participant"
  | "bpmn:ParticipantAssociation"
  | "bpmn:ParticipantMultiplicity"
  | "bpmn:PartnerEntity"
  | "bpmn:PartnerRole"
  | "bpmn:Performer"
  | "bpmn:PotentialOwner"
  | "bpmn:Process"
  | "bpmn:Property"
  | "bpmn:ReceiveTask"
  | "bpmn:Relationship"
  | "bpmn:Rendering"
  | "bpmn:Resource"
  | "bpmn:ResourceAssignmentExpression"
  | "bpmn:ResourceParameter"
  | "bpmn:ResourceParameterBinding"
  | "bpmn:ResourceRole"
  | "bpmn:ScriptTask"
  | "bpmn:SendTask"
  | "bpmn:SequenceFlow"
  | "bpmn:ServiceTask"
  | "bpmn:Signal"
  | "bpmn:SignalEventDefinition"
  | "bpmn:StandardLoopCharacteristics"
  | "bpmn:StartEvent"
  | "bpmn:SubChoreography"
  | "bpmn:SubConversation"
  | "bpmn:SubProcess"
  | "bpmn:Task"
  | "bpmn:TerminateEventDefinition"
  | "bpmn:TextAnnotation"
  | "bpmn:TimerEventDefinition"
  | "bpmn:Transaction"
  | "bpmn:UserTask"
  | "bpmndi:BPMNDiagram"
  | "bpmndi:BPMNEdge"
  | "bpmndi:BPMNLabel"
  | "bpmndi:BPMNLabelStyle"
  | "bpmndi:BPMNPlane"
  | "bpmndi:BPMNShape"
  | "dc:Boolean"
  | "dc:Bounds"
  | "dc:Font"
  | "dc:Integer"
  | "dc:Point"
  | "dc:Real"
  | "dc:String"
  | "di:Extension"
  | "zeebe:AdHoc"
  | "zeebe:AssignmentDefinition"
  | "zeebe:CalledDecision"
  | "zeebe:CalledElement"
  | "zeebe:ConditionalFilter"
  | "zeebe:ExecutionListener"
  | "zeebe:ExecutionListeners"
  | "zeebe:FormDefinition"
  | "zeebe:Header"
  | "zeebe:Input"
  | "zeebe:InputOutputParameter"
  | "zeebe:IoMapping"
  | "zeebe:JobPriorityDefinition"
  | "zeebe:LinkedResource"
  | "zeebe:LinkedResources"
  | "zeebe:LoopCharacteristics"
  | "zeebe:Output"
  | "zeebe:PriorityDefinition"
  | "zeebe:Properties"
  | "zeebe:Property"
  | "zeebe:Script"
  | "zeebe:Subscription"
  | "zeebe:TaskDefinition"
  | "zeebe:TaskHeaders"
  | "zeebe:TaskListener"
  | "zeebe:TaskListeners"
  | "zeebe:TaskSchedule"
  | "zeebe:UserTask"
  | "zeebe:UserTaskForm"
  | "zeebe:VersionTag"
>;

export type SupportedElementType = keyof ConstructibleModdleTypeMap;
type PropertiesFromMap<Type extends SupportedElementType> =
  Omit<ConstructibleModdleTypeMap[Type], keyof ModdleElement<object>>;
interface TraitProperties {
  "bpmn:AdHocSubProcess": ZeebeZeebeServiceTask;
  "bpmn:BusinessRuleTask": ZeebeZeebeServiceTask;
  "bpmn:Collaboration": ZeebeTemplateSupported;
  "bpmn:EndEvent": ZeebeZeebeServiceTask;
  "bpmn:Error": ZeebeTemplatedRootElement;
  "bpmn:Escalation": ZeebeTemplatedRootElement;
  "bpmn:FlowElement": ZeebeTemplateSupported;
  "bpmn:IntermediateThrowEvent": ZeebeZeebeServiceTask;
  "bpmn:Message": ZeebeTemplatedRootElement;
  "bpmn:Process": ZeebeTemplateSupported;
  "bpmn:ScriptTask": ZeebeZeebeServiceTask;
  "bpmn:SendTask": ZeebeZeebeServiceTask;
  "bpmn:ServiceTask": ZeebeZeebeServiceTask;
  "bpmn:Signal": ZeebeTemplatedRootElement;
  "zeebe:CalledDecision": ZeebeBindingTypeSupported;
  "zeebe:CalledElement": ZeebeBindingTypeSupported;
  "zeebe:FormDefinition": ZeebeBindingTypeSupported;
  "zeebe:Input": ZeebeConfigurationSupported;
  "zeebe:LinkedResource": ZeebeBindingTypeSupported;
  "zeebe:Property": ZeebeConfigurationSupported;
}
type TraitFields<Type extends SupportedElementType> =
  Type extends keyof TraitProperties ? TraitProperties[Type] : unknown;

export type ElementProperties<Type extends SupportedElementType> =
  PropertiesFromMap<Type> & TraitFields<Type>;

export const supportedElementTypes = [
  "bpmn:AdHocSubProcess",
  "bpmn:Assignment",
  "bpmn:Association",
  "bpmn:Auditing",
  "bpmn:BoundaryEvent",
  "bpmn:BusinessRuleTask",
  "bpmn:CallActivity",
  "bpmn:CallChoreography",
  "bpmn:CallConversation",
  "bpmn:CancelEventDefinition",
  "bpmn:Category",
  "bpmn:CategoryValue",
  "bpmn:Choreography",
  "bpmn:ChoreographyTask",
  "bpmn:Collaboration",
  "bpmn:CompensateEventDefinition",
  "bpmn:ComplexBehaviorDefinition",
  "bpmn:ComplexGateway",
  "bpmn:ConditionalEventDefinition",
  "bpmn:Conversation",
  "bpmn:ConversationAssociation",
  "bpmn:ConversationLink",
  "bpmn:CorrelationKey",
  "bpmn:CorrelationProperty",
  "bpmn:CorrelationPropertyBinding",
  "bpmn:CorrelationPropertyRetrievalExpression",
  "bpmn:CorrelationSubscription",
  "bpmn:DataAssociation",
  "bpmn:DataInput",
  "bpmn:DataInputAssociation",
  "bpmn:DataObject",
  "bpmn:DataObjectReference",
  "bpmn:DataOutput",
  "bpmn:DataOutputAssociation",
  "bpmn:DataState",
  "bpmn:DataStore",
  "bpmn:DataStoreReference",
  "bpmn:Definitions",
  "bpmn:Documentation",
  "bpmn:EndEvent",
  "bpmn:EndPoint",
  "bpmn:Error",
  "bpmn:ErrorEventDefinition",
  "bpmn:Escalation",
  "bpmn:EscalationEventDefinition",
  "bpmn:EventBasedGateway",
  "bpmn:ExclusiveGateway",
  "bpmn:Expression",
  "bpmn:Extension",
  "bpmn:ExtensionAttributeDefinition",
  "bpmn:ExtensionDefinition",
  "bpmn:ExtensionElements",
  "bpmn:FormalExpression",
  "bpmn:GlobalBusinessRuleTask",
  "bpmn:GlobalChoreographyTask",
  "bpmn:GlobalConversation",
  "bpmn:GlobalManualTask",
  "bpmn:GlobalScriptTask",
  "bpmn:GlobalTask",
  "bpmn:GlobalUserTask",
  "bpmn:Group",
  "bpmn:HumanPerformer",
  "bpmn:ImplicitThrowEvent",
  "bpmn:Import",
  "bpmn:InclusiveGateway",
  "bpmn:InputOutputBinding",
  "bpmn:InputOutputSpecification",
  "bpmn:InputSet",
  "bpmn:Interface",
  "bpmn:IntermediateCatchEvent",
  "bpmn:IntermediateThrowEvent",
  "bpmn:ItemAwareElement",
  "bpmn:ItemDefinition",
  "bpmn:Lane",
  "bpmn:LaneSet",
  "bpmn:LinkEventDefinition",
  "bpmn:ManualTask",
  "bpmn:Message",
  "bpmn:MessageEventDefinition",
  "bpmn:MessageFlow",
  "bpmn:MessageFlowAssociation",
  "bpmn:Monitoring",
  "bpmn:MultiInstanceLoopCharacteristics",
  "bpmn:Operation",
  "bpmn:OutputSet",
  "bpmn:ParallelGateway",
  "bpmn:Participant",
  "bpmn:ParticipantAssociation",
  "bpmn:ParticipantMultiplicity",
  "bpmn:PartnerEntity",
  "bpmn:PartnerRole",
  "bpmn:Performer",
  "bpmn:PotentialOwner",
  "bpmn:Process",
  "bpmn:Property",
  "bpmn:ReceiveTask",
  "bpmn:Relationship",
  "bpmn:Rendering",
  "bpmn:Resource",
  "bpmn:ResourceAssignmentExpression",
  "bpmn:ResourceParameter",
  "bpmn:ResourceParameterBinding",
  "bpmn:ResourceRole",
  "bpmn:ScriptTask",
  "bpmn:SendTask",
  "bpmn:SequenceFlow",
  "bpmn:ServiceTask",
  "bpmn:Signal",
  "bpmn:SignalEventDefinition",
  "bpmn:StandardLoopCharacteristics",
  "bpmn:StartEvent",
  "bpmn:SubChoreography",
  "bpmn:SubConversation",
  "bpmn:SubProcess",
  "bpmn:Task",
  "bpmn:TerminateEventDefinition",
  "bpmn:TextAnnotation",
  "bpmn:TimerEventDefinition",
  "bpmn:Transaction",
  "bpmn:UserTask",
  "bpmndi:BPMNDiagram",
  "bpmndi:BPMNEdge",
  "bpmndi:BPMNLabel",
  "bpmndi:BPMNLabelStyle",
  "bpmndi:BPMNPlane",
  "bpmndi:BPMNShape",
  "dc:Boolean",
  "dc:Bounds",
  "dc:Font",
  "dc:Integer",
  "dc:Point",
  "dc:Real",
  "dc:String",
  "di:Extension",
  "zeebe:AdHoc",
  "zeebe:AssignmentDefinition",
  "zeebe:CalledDecision",
  "zeebe:CalledElement",
  "zeebe:ConditionalFilter",
  "zeebe:ExecutionListener",
  "zeebe:ExecutionListeners",
  "zeebe:FormDefinition",
  "zeebe:Header",
  "zeebe:Input",
  "zeebe:InputOutputParameter",
  "zeebe:IoMapping",
  "zeebe:JobPriorityDefinition",
  "zeebe:LinkedResource",
  "zeebe:LinkedResources",
  "zeebe:LoopCharacteristics",
  "zeebe:Output",
  "zeebe:PriorityDefinition",
  "zeebe:Properties",
  "zeebe:Property",
  "zeebe:Script",
  "zeebe:Subscription",
  "zeebe:TaskDefinition",
  "zeebe:TaskHeaders",
  "zeebe:TaskListener",
  "zeebe:TaskListeners",
  "zeebe:TaskSchedule",
  "zeebe:UserTask",
  "zeebe:UserTaskForm",
  "zeebe:VersionTag",
] as const satisfies readonly SupportedElementType[];
