// This file is generated by scripts/generate-model-types.mjs. Do not edit.
// Descriptor SHA-256: 615978b99d190e3792ac8054e905f6b4db18aa8f679313f2ce58282d21e32273

import type { ModdleElement } from "bpmn-moddle";

export interface ModdleTypeMap {
  "bpmn:AdHocSubProcess": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "triggeredByEvent"?: boolean;
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "completionCondition"?: ModdleElement;
    readonly "ordering"?: ModdleElement;
    readonly "cancelRemainingInstances"?: boolean;
  };
  "bpmn:Assignment": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "from"?: ModdleElement;
    readonly "to"?: ModdleElement;
  };
  "bpmn:Association": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "associationDirection"?: ModdleElement;
    readonly "sourceRef"?: ModdleElement;
    readonly "targetRef"?: ModdleElement;
  };
  "bpmn:Auditing": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
  };
  "bpmn:BoundaryEvent": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "parallelMultiple"?: boolean;
    readonly "dataOutputs"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "outputSet"?: ModdleElement;
    readonly "eventDefinitions"?: readonly ModdleElement[];
    readonly "eventDefinitionRef"?: readonly ModdleElement[];
    readonly "cancelActivity"?: boolean;
    readonly "attachedToRef"?: ModdleElement;
  };
  "bpmn:BusinessRuleTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "implementation"?: string;
  };
  "bpmn:CallActivity": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "calledElement"?: string;
  };
  "bpmn:CallChoreography": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "participantRef"?: readonly ModdleElement[];
    readonly "initiatingParticipantRef"?: ModdleElement;
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "loopType"?: ModdleElement;
    readonly "calledChoreographyRef"?: ModdleElement;
    readonly "participantAssociations"?: readonly ModdleElement[];
  };
  "bpmn:CallConversation": {
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "participantRef"?: readonly ModdleElement[];
    readonly "messageFlowRefs"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "calledCollaborationRef"?: ModdleElement;
    readonly "participantAssociations"?: readonly ModdleElement[];
  };
  "bpmn:CancelEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
  };
  "bpmn:Category": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "categoryValue"?: readonly ModdleElement[];
    readonly "name"?: string;
  };
  "bpmn:CategoryValue": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "categorizedFlowElements"?: readonly ModdleElement[];
    readonly "value"?: string;
  };
  "bpmn:Choreography": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "isClosed"?: boolean;
    readonly "participants"?: readonly ModdleElement[];
    readonly "messageFlows"?: readonly ModdleElement[];
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "conversations"?: readonly ModdleElement[];
    readonly "conversationAssociations"?: ModdleElement;
    readonly "participantAssociations"?: readonly ModdleElement[];
    readonly "messageFlowAssociations"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "choreographyRef"?: readonly ModdleElement[];
    readonly "conversationLinks"?: readonly ModdleElement[];
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
  };
  "bpmn:ChoreographyTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "participantRef"?: readonly ModdleElement[];
    readonly "initiatingParticipantRef"?: ModdleElement;
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "loopType"?: ModdleElement;
    readonly "messageFlowRef"?: readonly ModdleElement[];
  };
  "bpmn:Collaboration": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "isClosed"?: boolean;
    readonly "participants"?: readonly ModdleElement[];
    readonly "messageFlows"?: readonly ModdleElement[];
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "conversations"?: readonly ModdleElement[];
    readonly "conversationAssociations"?: ModdleElement;
    readonly "participantAssociations"?: readonly ModdleElement[];
    readonly "messageFlowAssociations"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "choreographyRef"?: readonly ModdleElement[];
    readonly "conversationLinks"?: readonly ModdleElement[];
  };
  "bpmn:CompensateEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "waitForCompletion"?: boolean;
    readonly "activityRef"?: ModdleElement;
  };
  "bpmn:ComplexBehaviorDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "condition"?: ModdleElement;
    readonly "event"?: ModdleElement;
  };
  "bpmn:ComplexGateway": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "gatewayDirection"?: ModdleElement;
    readonly "activationCondition"?: ModdleElement;
    readonly "default"?: ModdleElement;
  };
  "bpmn:ConditionalEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "condition"?: ModdleElement;
  };
  "bpmn:Conversation": {
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "participantRef"?: readonly ModdleElement[];
    readonly "messageFlowRefs"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
  };
  "bpmn:ConversationAssociation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "innerConversationNodeRef"?: ModdleElement;
    readonly "outerConversationNodeRef"?: ModdleElement;
  };
  "bpmn:ConversationLink": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "sourceRef"?: ModdleElement;
    readonly "targetRef"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:CorrelationKey": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "correlationPropertyRef"?: readonly ModdleElement[];
    readonly "name"?: string;
  };
  "bpmn:CorrelationProperty": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "correlationPropertyRetrievalExpression"?: readonly ModdleElement[];
    readonly "name"?: string;
    readonly "type"?: ModdleElement;
  };
  "bpmn:CorrelationPropertyBinding": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "dataPath"?: ModdleElement;
    readonly "correlationPropertyRef"?: ModdleElement;
  };
  "bpmn:CorrelationPropertyRetrievalExpression": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "messagePath"?: ModdleElement;
    readonly "messageRef"?: ModdleElement;
  };
  "bpmn:CorrelationSubscription": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "correlationKeyRef"?: ModdleElement;
    readonly "correlationPropertyBinding"?: readonly ModdleElement[];
  };
  "bpmn:DataAssociation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "sourceRef"?: readonly ModdleElement[];
    readonly "targetRef"?: ModdleElement;
    readonly "transformation"?: ModdleElement;
    readonly "assignment"?: readonly ModdleElement[];
  };
  "bpmn:DataInput": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "name"?: string;
    readonly "isCollection"?: boolean;
    readonly "inputSetRef"?: readonly ModdleElement[];
    readonly "inputSetWithOptional"?: readonly ModdleElement[];
    readonly "inputSetWithWhileExecuting"?: readonly ModdleElement[];
  };
  "bpmn:DataInputAssociation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "sourceRef"?: readonly ModdleElement[];
    readonly "targetRef"?: ModdleElement;
    readonly "transformation"?: ModdleElement;
    readonly "assignment"?: readonly ModdleElement[];
  };
  "bpmn:DataObject": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "isCollection"?: boolean;
  };
  "bpmn:DataObjectReference": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "dataObjectRef"?: ModdleElement;
  };
  "bpmn:DataOutput": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "name"?: string;
    readonly "isCollection"?: boolean;
    readonly "outputSetRef"?: readonly ModdleElement[];
    readonly "outputSetWithOptional"?: readonly ModdleElement[];
    readonly "outputSetWithWhileExecuting"?: readonly ModdleElement[];
  };
  "bpmn:DataOutputAssociation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "sourceRef"?: readonly ModdleElement[];
    readonly "targetRef"?: ModdleElement;
    readonly "transformation"?: ModdleElement;
    readonly "assignment"?: readonly ModdleElement[];
  };
  "bpmn:DataState": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:DataStore": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "name"?: string;
    readonly "capacity"?: number;
    readonly "isUnlimited"?: boolean;
  };
  "bpmn:DataStoreReference": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "dataStoreRef"?: ModdleElement;
  };
  "bpmn:Definitions": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "targetNamespace"?: string;
    readonly "expressionLanguage"?: string;
    readonly "typeLanguage"?: string;
    readonly "imports"?: readonly ModdleElement[];
    readonly "extensions"?: readonly ModdleElement[];
    readonly "rootElements"?: readonly ModdleElement[];
    readonly "diagrams"?: readonly ModdleElement[];
    readonly "exporter"?: string;
    readonly "relationships"?: readonly ModdleElement[];
    readonly "exporterVersion"?: string;
  };
  "bpmn:Documentation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "text"?: string;
    readonly "textFormat"?: string;
  };
  "bpmn:EndEvent": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputs"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "inputSet"?: ModdleElement;
    readonly "eventDefinitions"?: readonly ModdleElement[];
    readonly "eventDefinitionRef"?: readonly ModdleElement[];
  };
  "bpmn:EndPoint": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
  };
  "bpmn:Error": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "structureRef"?: ModdleElement;
    readonly "name"?: string;
    readonly "errorCode"?: string;
  };
  "bpmn:ErrorEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "errorRef"?: ModdleElement;
  };
  "bpmn:Escalation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "structureRef"?: ModdleElement;
    readonly "name"?: string;
    readonly "escalationCode"?: string;
  };
  "bpmn:EscalationEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "escalationRef"?: ModdleElement;
  };
  "bpmn:EventBasedGateway": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "gatewayDirection"?: ModdleElement;
    readonly "instantiate"?: boolean;
    readonly "eventGatewayType"?: ModdleElement;
  };
  "bpmn:ExclusiveGateway": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "gatewayDirection"?: ModdleElement;
    readonly "default"?: ModdleElement;
  };
  "bpmn:Expression": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "body"?: string;
  };
  "bpmn:Extension": {
    readonly "mustUnderstand"?: boolean;
    readonly "definition"?: ModdleElement;
  };
  "bpmn:ExtensionAttributeDefinition": {
    readonly "name"?: string;
    readonly "type"?: string;
    readonly "isReference"?: boolean;
    readonly "extensionDefinition"?: ModdleElement;
  };
  "bpmn:ExtensionDefinition": {
    readonly "name"?: string;
    readonly "extensionAttributeDefinitions"?: readonly ModdleElement[];
  };
  "bpmn:ExtensionElements": {
    readonly "valueRef"?: ModdleElement;
    readonly "values"?: readonly ModdleElement[];
    readonly "extensionAttributeDefinition"?: ModdleElement;
  };
  "bpmn:FormalExpression": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "body"?: string;
    readonly "language"?: string;
    readonly "evaluatesToTypeRef"?: ModdleElement;
  };
  "bpmn:GlobalBusinessRuleTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "ioSpecification"?: ModdleElement;
    readonly "supportedInterfaceRef"?: readonly ModdleElement[];
    readonly "ioBinding"?: readonly ModdleElement[];
    readonly "resources"?: readonly ModdleElement[];
    readonly "implementation"?: string;
  };
  "bpmn:GlobalChoreographyTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "isClosed"?: boolean;
    readonly "participants"?: readonly ModdleElement[];
    readonly "messageFlows"?: readonly ModdleElement[];
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "conversations"?: readonly ModdleElement[];
    readonly "conversationAssociations"?: ModdleElement;
    readonly "participantAssociations"?: readonly ModdleElement[];
    readonly "messageFlowAssociations"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "choreographyRef"?: readonly ModdleElement[];
    readonly "conversationLinks"?: readonly ModdleElement[];
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
    readonly "initiatingParticipantRef"?: ModdleElement;
  };
  "bpmn:GlobalConversation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "isClosed"?: boolean;
    readonly "participants"?: readonly ModdleElement[];
    readonly "messageFlows"?: readonly ModdleElement[];
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "conversations"?: readonly ModdleElement[];
    readonly "conversationAssociations"?: ModdleElement;
    readonly "participantAssociations"?: readonly ModdleElement[];
    readonly "messageFlowAssociations"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "choreographyRef"?: readonly ModdleElement[];
    readonly "conversationLinks"?: readonly ModdleElement[];
  };
  "bpmn:GlobalManualTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "ioSpecification"?: ModdleElement;
    readonly "supportedInterfaceRef"?: readonly ModdleElement[];
    readonly "ioBinding"?: readonly ModdleElement[];
    readonly "resources"?: readonly ModdleElement[];
  };
  "bpmn:GlobalScriptTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "ioSpecification"?: ModdleElement;
    readonly "supportedInterfaceRef"?: readonly ModdleElement[];
    readonly "ioBinding"?: readonly ModdleElement[];
    readonly "resources"?: readonly ModdleElement[];
    readonly "scriptLanguage"?: string;
    readonly "script"?: string;
  };
  "bpmn:GlobalTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "ioSpecification"?: ModdleElement;
    readonly "supportedInterfaceRef"?: readonly ModdleElement[];
    readonly "ioBinding"?: readonly ModdleElement[];
    readonly "resources"?: readonly ModdleElement[];
  };
  "bpmn:GlobalUserTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "ioSpecification"?: ModdleElement;
    readonly "supportedInterfaceRef"?: readonly ModdleElement[];
    readonly "ioBinding"?: readonly ModdleElement[];
    readonly "resources"?: readonly ModdleElement[];
    readonly "implementation"?: string;
    readonly "renderings"?: readonly ModdleElement[];
  };
  "bpmn:Group": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "categoryValueRef"?: ModdleElement;
  };
  "bpmn:HumanPerformer": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "resourceRef"?: ModdleElement;
    readonly "resourceParameterBindings"?: readonly ModdleElement[];
    readonly "resourceAssignmentExpression"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:ImplicitThrowEvent": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputs"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "inputSet"?: ModdleElement;
    readonly "eventDefinitions"?: readonly ModdleElement[];
    readonly "eventDefinitionRef"?: readonly ModdleElement[];
  };
  "bpmn:Import": {
    readonly "importType"?: string;
    readonly "location"?: string;
    readonly "namespace"?: string;
  };
  "bpmn:InclusiveGateway": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "gatewayDirection"?: ModdleElement;
    readonly "default"?: ModdleElement;
  };
  "bpmn:InputOutputBinding": {
    readonly "inputDataRef"?: ModdleElement;
    readonly "outputDataRef"?: ModdleElement;
    readonly "operationRef"?: ModdleElement;
  };
  "bpmn:InputOutputSpecification": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "dataInputs"?: readonly ModdleElement[];
    readonly "dataOutputs"?: readonly ModdleElement[];
    readonly "inputSets"?: readonly ModdleElement[];
    readonly "outputSets"?: readonly ModdleElement[];
  };
  "bpmn:InputSet": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "dataInputRefs"?: readonly ModdleElement[];
    readonly "optionalInputRefs"?: readonly ModdleElement[];
    readonly "whileExecutingInputRefs"?: readonly ModdleElement[];
    readonly "outputSetRefs"?: readonly ModdleElement[];
  };
  "bpmn:Interface": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "operations"?: readonly ModdleElement[];
    readonly "implementationRef"?: string;
  };
  "bpmn:IntermediateCatchEvent": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "parallelMultiple"?: boolean;
    readonly "dataOutputs"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "outputSet"?: ModdleElement;
    readonly "eventDefinitions"?: readonly ModdleElement[];
    readonly "eventDefinitionRef"?: readonly ModdleElement[];
  };
  "bpmn:IntermediateThrowEvent": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputs"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "inputSet"?: ModdleElement;
    readonly "eventDefinitions"?: readonly ModdleElement[];
    readonly "eventDefinitionRef"?: readonly ModdleElement[];
  };
  "bpmn:ItemAwareElement": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
  };
  "bpmn:ItemDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemKind"?: ModdleElement;
    readonly "structureRef"?: string;
    readonly "isCollection"?: boolean;
    readonly "import"?: ModdleElement;
  };
  "bpmn:Lane": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "partitionElementRef"?: ModdleElement;
    readonly "partitionElement"?: ModdleElement;
    readonly "flowNodeRef"?: readonly ModdleElement[];
    readonly "childLaneSet"?: ModdleElement;
  };
  "bpmn:LaneSet": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "lanes"?: readonly ModdleElement[];
    readonly "name"?: string;
  };
  "bpmn:LinkEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "target"?: ModdleElement;
    readonly "source"?: readonly ModdleElement[];
  };
  "bpmn:ManualTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
  };
  "bpmn:Message": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "itemRef"?: ModdleElement;
  };
  "bpmn:MessageEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "messageRef"?: ModdleElement;
    readonly "operationRef"?: ModdleElement;
  };
  "bpmn:MessageFlow": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "sourceRef"?: ModdleElement;
    readonly "targetRef"?: ModdleElement;
    readonly "messageRef"?: ModdleElement;
  };
  "bpmn:MessageFlowAssociation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "innerMessageFlowRef"?: ModdleElement;
    readonly "outerMessageFlowRef"?: ModdleElement;
  };
  "bpmn:Monitoring": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
  };
  "bpmn:MultiInstanceLoopCharacteristics": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "isSequential"?: boolean;
    readonly "behavior"?: ModdleElement;
    readonly "loopCardinality"?: ModdleElement;
    readonly "loopDataInputRef"?: ModdleElement;
    readonly "loopDataOutputRef"?: ModdleElement;
    readonly "inputDataItem"?: ModdleElement;
    readonly "outputDataItem"?: ModdleElement;
    readonly "complexBehaviorDefinition"?: readonly ModdleElement[];
    readonly "completionCondition"?: ModdleElement;
    readonly "oneBehaviorEventRef"?: ModdleElement;
    readonly "noneBehaviorEventRef"?: ModdleElement;
  };
  "bpmn:Operation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "inMessageRef"?: ModdleElement;
    readonly "outMessageRef"?: ModdleElement;
    readonly "errorRef"?: readonly ModdleElement[];
    readonly "implementationRef"?: string;
  };
  "bpmn:OutputSet": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "dataOutputRefs"?: readonly ModdleElement[];
    readonly "name"?: string;
    readonly "inputSetRefs"?: readonly ModdleElement[];
    readonly "optionalOutputRefs"?: readonly ModdleElement[];
    readonly "whileExecutingOutputRefs"?: readonly ModdleElement[];
  };
  "bpmn:ParallelGateway": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "gatewayDirection"?: ModdleElement;
  };
  "bpmn:Participant": {
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "interfaceRef"?: readonly ModdleElement[];
    readonly "participantMultiplicity"?: ModdleElement;
    readonly "endPointRefs"?: readonly ModdleElement[];
    readonly "processRef"?: ModdleElement;
  };
  "bpmn:ParticipantAssociation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "innerParticipantRef"?: ModdleElement;
    readonly "outerParticipantRef"?: ModdleElement;
  };
  "bpmn:ParticipantMultiplicity": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "minimum"?: number;
    readonly "maximum"?: number;
  };
  "bpmn:PartnerEntity": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "participantRef"?: readonly ModdleElement[];
  };
  "bpmn:PartnerRole": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "participantRef"?: readonly ModdleElement[];
  };
  "bpmn:Performer": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "resourceRef"?: ModdleElement;
    readonly "resourceParameterBindings"?: readonly ModdleElement[];
    readonly "resourceAssignmentExpression"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:PotentialOwner": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "resourceRef"?: ModdleElement;
    readonly "resourceParameterBindings"?: readonly ModdleElement[];
    readonly "resourceAssignmentExpression"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:Process": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
    readonly "name"?: string;
    readonly "ioSpecification"?: ModdleElement;
    readonly "supportedInterfaceRef"?: readonly ModdleElement[];
    readonly "ioBinding"?: readonly ModdleElement[];
    readonly "processType"?: ModdleElement;
    readonly "isClosed"?: boolean;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "properties"?: readonly ModdleElement[];
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "resources"?: readonly ModdleElement[];
    readonly "correlationSubscriptions"?: readonly ModdleElement[];
    readonly "supports"?: readonly ModdleElement[];
    readonly "definitionalCollaborationRef"?: ModdleElement;
    readonly "isExecutable"?: boolean;
  };
  "bpmn:Property": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "itemSubjectRef"?: ModdleElement;
    readonly "dataState"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:ReceiveTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "implementation"?: string;
    readonly "instantiate"?: boolean;
    readonly "operationRef"?: ModdleElement;
    readonly "messageRef"?: ModdleElement;
  };
  "bpmn:Relationship": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "type"?: string;
    readonly "direction"?: ModdleElement;
    readonly "source"?: readonly ModdleElement[];
    readonly "target"?: readonly ModdleElement[];
  };
  "bpmn:Rendering": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
  };
  "bpmn:Resource": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "resourceParameters"?: readonly ModdleElement[];
  };
  "bpmn:ResourceAssignmentExpression": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "expression"?: ModdleElement;
  };
  "bpmn:ResourceParameter": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "isRequired"?: boolean;
    readonly "type"?: ModdleElement;
  };
  "bpmn:ResourceParameterBinding": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "expression"?: ModdleElement;
    readonly "parameterRef"?: ModdleElement;
  };
  "bpmn:ResourceRole": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "resourceRef"?: ModdleElement;
    readonly "resourceParameterBindings"?: readonly ModdleElement[];
    readonly "resourceAssignmentExpression"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:ScriptTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "scriptFormat"?: string;
    readonly "script"?: string;
  };
  "bpmn:SendTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "implementation"?: string;
    readonly "operationRef"?: ModdleElement;
    readonly "messageRef"?: ModdleElement;
  };
  "bpmn:SequenceFlow": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "isImmediate"?: boolean;
    readonly "conditionExpression"?: ModdleElement;
    readonly "sourceRef"?: ModdleElement;
    readonly "targetRef"?: ModdleElement;
  };
  "bpmn:ServiceTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "implementation"?: string;
    readonly "operationRef"?: ModdleElement;
  };
  "bpmn:Signal": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "structureRef"?: ModdleElement;
    readonly "name"?: string;
  };
  "bpmn:SignalEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "signalRef"?: ModdleElement;
  };
  "bpmn:StandardLoopCharacteristics": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "testBefore"?: boolean;
    readonly "loopCondition"?: ModdleElement;
    readonly "loopMaximum"?: number;
  };
  "bpmn:StartEvent": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "parallelMultiple"?: boolean;
    readonly "dataOutputs"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "outputSet"?: ModdleElement;
    readonly "eventDefinitions"?: readonly ModdleElement[];
    readonly "eventDefinitionRef"?: readonly ModdleElement[];
    readonly "isInterrupting"?: boolean;
  };
  "bpmn:SubChoreography": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "participantRef"?: readonly ModdleElement[];
    readonly "initiatingParticipantRef"?: ModdleElement;
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "loopType"?: ModdleElement;
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
    readonly "artifacts"?: readonly ModdleElement[];
  };
  "bpmn:SubConversation": {
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "participantRef"?: readonly ModdleElement[];
    readonly "messageFlowRefs"?: readonly ModdleElement[];
    readonly "correlationKeys"?: readonly ModdleElement[];
    readonly "conversationNodes"?: readonly ModdleElement[];
  };
  "bpmn:SubProcess": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "triggeredByEvent"?: boolean;
    readonly "artifacts"?: readonly ModdleElement[];
  };
  "bpmn:Task": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
  };
  "bpmn:TerminateEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
  };
  "bpmn:TextAnnotation": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "text"?: string;
    readonly "textFormat"?: string;
  };
  "bpmn:TimerEventDefinition": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "timeDate"?: ModdleElement;
    readonly "timeCycle"?: ModdleElement;
    readonly "timeDuration"?: ModdleElement;
  };
  "bpmn:Transaction": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "laneSets"?: readonly ModdleElement[];
    readonly "flowElements"?: readonly ModdleElement[];
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "triggeredByEvent"?: boolean;
    readonly "artifacts"?: readonly ModdleElement[];
    readonly "protocol"?: string;
    readonly "method"?: string;
  };
  "bpmn:UserTask": {
    readonly "id"?: string;
    readonly "documentation"?: readonly ModdleElement[];
    readonly "extensionDefinitions"?: readonly ModdleElement[];
    readonly "extensionElements"?: ModdleElement;
    readonly "name"?: string;
    readonly "auditing"?: ModdleElement;
    readonly "monitoring"?: ModdleElement;
    readonly "categoryValueRef"?: readonly ModdleElement[];
    readonly "incoming"?: readonly ModdleElement[];
    readonly "outgoing"?: readonly ModdleElement[];
    readonly "lanes"?: readonly ModdleElement[];
    readonly "isForCompensation"?: boolean;
    readonly "default"?: ModdleElement;
    readonly "ioSpecification"?: ModdleElement;
    readonly "boundaryEventRefs"?: readonly ModdleElement[];
    readonly "properties"?: readonly ModdleElement[];
    readonly "dataInputAssociations"?: readonly ModdleElement[];
    readonly "dataOutputAssociations"?: readonly ModdleElement[];
    readonly "startQuantity"?: number;
    readonly "resources"?: readonly ModdleElement[];
    readonly "completionQuantity"?: number;
    readonly "loopCharacteristics"?: ModdleElement;
    readonly "incomingConversationLinks"?: readonly ModdleElement[];
    readonly "outgoingConversationLinks"?: readonly ModdleElement[];
    readonly "renderings"?: readonly ModdleElement[];
    readonly "implementation"?: string;
  };
  "bpmndi:BPMNDiagram": {
    readonly "id"?: string;
    readonly "rootElement"?: ModdleElement;
    readonly "name"?: string;
    readonly "documentation"?: string;
    readonly "resolution"?: number;
    readonly "ownedStyle"?: readonly ModdleElement[];
    readonly "plane"?: ModdleElement;
    readonly "labelStyle"?: readonly ModdleElement[];
  };
  "bpmndi:BPMNEdge": {
    readonly "id"?: string;
    readonly "extension"?: ModdleElement;
    readonly "owningDiagram"?: ModdleElement;
    readonly "owningElement"?: ModdleElement;
    readonly "modelElement"?: ModdleElement;
    readonly "style"?: ModdleElement;
    readonly "ownedElement"?: readonly ModdleElement[];
    readonly "source"?: ModdleElement;
    readonly "target"?: ModdleElement;
    readonly "waypoint"?: readonly ModdleElement[];
    readonly "ownedLabel"?: readonly ModdleElement[];
    readonly "label"?: ModdleElement;
    readonly "bpmnElement"?: ModdleElement;
    readonly "sourceElement"?: ModdleElement;
    readonly "targetElement"?: ModdleElement;
    readonly "messageVisibleKind"?: ModdleElement;
  };
  "bpmndi:BPMNLabel": {
    readonly "id"?: string;
    readonly "extension"?: ModdleElement;
    readonly "owningDiagram"?: ModdleElement;
    readonly "owningElement"?: ModdleElement;
    readonly "modelElement"?: ModdleElement;
    readonly "style"?: ModdleElement;
    readonly "ownedElement"?: readonly ModdleElement[];
    readonly "bounds"?: ModdleElement;
    readonly "labelStyle"?: ModdleElement;
  };
  "bpmndi:BPMNLabelStyle": {
    readonly "id"?: string;
    readonly "font"?: ModdleElement;
  };
  "bpmndi:BPMNPlane": {
    readonly "id"?: string;
    readonly "extension"?: ModdleElement;
    readonly "owningDiagram"?: ModdleElement;
    readonly "owningElement"?: ModdleElement;
    readonly "modelElement"?: ModdleElement;
    readonly "style"?: ModdleElement;
    readonly "ownedElement"?: readonly ModdleElement[];
    readonly "planeElement"?: readonly ModdleElement[];
    readonly "bpmnElement"?: ModdleElement;
  };
  "bpmndi:BPMNShape": {
    readonly "id"?: string;
    readonly "extension"?: ModdleElement;
    readonly "owningDiagram"?: ModdleElement;
    readonly "owningElement"?: ModdleElement;
    readonly "modelElement"?: ModdleElement;
    readonly "style"?: ModdleElement;
    readonly "ownedElement"?: readonly ModdleElement[];
    readonly "bounds"?: ModdleElement;
    readonly "ownedLabel"?: readonly ModdleElement[];
    readonly "bpmnElement"?: ModdleElement;
    readonly "isHorizontal"?: boolean;
    readonly "isExpanded"?: boolean;
    readonly "isMarkerVisible"?: boolean;
    readonly "label"?: ModdleElement;
    readonly "isMessageVisible"?: boolean;
    readonly "participantBandKind"?: ModdleElement;
    readonly "choreographyActivityShape"?: ModdleElement;
  };
  "dc:Boolean": Record<never, never>;
  "dc:Bounds": {
    readonly "x"?: number;
    readonly "y"?: number;
    readonly "width"?: number;
    readonly "height"?: number;
  };
  "dc:Font": {
    readonly "name"?: string;
    readonly "size"?: number;
    readonly "isBold"?: boolean;
    readonly "isItalic"?: boolean;
    readonly "isUnderline"?: boolean;
    readonly "isStrikeThrough"?: boolean;
  };
  "dc:Integer": Record<never, never>;
  "dc:Point": {
    readonly "x"?: number;
    readonly "y"?: number;
  };
  "dc:Real": Record<never, never>;
  "dc:String": Record<never, never>;
  "di:Extension": {
    readonly "values"?: readonly ModdleElement[];
  };
  "zeebe:AdHoc": {
    readonly "activeElementsCollection"?: string;
    readonly "outputCollection"?: string;
    readonly "outputElement"?: string;
  };
  "zeebe:AssignmentDefinition": {
    readonly "assignee"?: string;
    readonly "candidateGroups"?: string;
    readonly "candidateUsers"?: string;
  };
  "zeebe:CalledDecision": {
    readonly "decisionId"?: string;
    readonly "resultVariable"?: string;
  };
  "zeebe:CalledElement": {
    readonly "processId"?: string;
    readonly "processIdExpression"?: string;
    readonly "propagateAllChildVariables"?: boolean;
    readonly "propagateAllParentVariables"?: boolean;
  };
  "zeebe:ConditionalFilter": {
    readonly "variableNames"?: string;
    readonly "variableEvents"?: string;
  };
  "zeebe:ExecutionListener": {
    readonly "eventType"?: string;
    readonly "retries"?: string;
    readonly "type"?: string;
    readonly "headers"?: ModdleElement;
  };
  "zeebe:ExecutionListeners": {
    readonly "listeners"?: readonly ModdleElement[];
  };
  "zeebe:FormDefinition": {
    readonly "formKey"?: string;
    readonly "formId"?: string;
    readonly "externalReference"?: string;
  };
  "zeebe:Header": {
    readonly "id"?: string;
    readonly "key"?: string;
    readonly "value"?: string;
  };
  "zeebe:Input": {
    readonly "source"?: string;
    readonly "target"?: string;
  };
  "zeebe:InputOutputParameter": {
    readonly "source"?: string;
    readonly "target"?: string;
  };
  "zeebe:IoMapping": {
    readonly "ioMapping"?: ModdleElement;
    readonly "inputParameters"?: readonly ModdleElement[];
    readonly "outputParameters"?: readonly ModdleElement[];
  };
  "zeebe:JobPriorityDefinition": {
    readonly "priority"?: string;
  };
  "zeebe:LinkedResource": {
    readonly "resourceId"?: string;
    readonly "resourceType"?: string;
    readonly "linkName"?: string;
  };
  "zeebe:LinkedResources": {
    readonly "values"?: readonly ModdleElement[];
  };
  "zeebe:LoopCharacteristics": {
    readonly "inputCollection"?: string;
    readonly "inputElement"?: string;
    readonly "outputCollection"?: string;
    readonly "outputElement"?: string;
  };
  "zeebe:Output": {
    readonly "source"?: string;
    readonly "target"?: string;
  };
  "zeebe:PriorityDefinition": {
    readonly "priority"?: string;
  };
  "zeebe:Properties": {
    readonly "properties"?: readonly ModdleElement[];
  };
  "zeebe:Property": {
    readonly "name"?: string;
    readonly "value"?: string;
  };
  "zeebe:Script": {
    readonly "expression"?: string;
    readonly "resultVariable"?: string;
  };
  "zeebe:Subscription": {
    readonly "correlationKey"?: string;
  };
  "zeebe:TaskDefinition": {
    readonly "type"?: string;
    readonly "retries"?: string;
  };
  "zeebe:TaskHeaders": {
    readonly "values"?: readonly ModdleElement[];
  };
  "zeebe:TaskListener": {
    readonly "eventType"?: string;
    readonly "retries"?: string;
    readonly "type"?: string;
  };
  "zeebe:TaskListeners": {
    readonly "listeners"?: readonly ModdleElement[];
  };
  "zeebe:TaskSchedule": {
    readonly "dueDate"?: string;
    readonly "followUpDate"?: string;
  };
  "zeebe:UserTask": Record<never, never>;
  "zeebe:UserTaskForm": {
    readonly "id"?: string;
    readonly "body"?: string;
  };
  "zeebe:VersionTag": {
    readonly "value"?: string;
  };
  "zeebe:ZeebeServiceTask": {
    readonly "retryCounter"?: string;
  };
}

export type SupportedElementType = keyof ModdleTypeMap;
export type ElementProperties<Type extends SupportedElementType> = ModdleTypeMap[Type];
export const supportedElementTypes = [
  "bpmn:AdHocSubProcess",
  "bpmn:Assignment",
  "bpmn:Association",
  "bpmn:Auditing",
  "bpmn:BoundaryEvent",
  "bpmn:BusinessRuleTask",
  "bpmn:CallActivity",
  "bpmn:CallChoreography",
  "bpmn:CallConversation",
  "bpmn:CancelEventDefinition",
  "bpmn:Category",
  "bpmn:CategoryValue",
  "bpmn:Choreography",
  "bpmn:ChoreographyTask",
  "bpmn:Collaboration",
  "bpmn:CompensateEventDefinition",
  "bpmn:ComplexBehaviorDefinition",
  "bpmn:ComplexGateway",
  "bpmn:ConditionalEventDefinition",
  "bpmn:Conversation",
  "bpmn:ConversationAssociation",
  "bpmn:ConversationLink",
  "bpmn:CorrelationKey",
  "bpmn:CorrelationProperty",
  "bpmn:CorrelationPropertyBinding",
  "bpmn:CorrelationPropertyRetrievalExpression",
  "bpmn:CorrelationSubscription",
  "bpmn:DataAssociation",
  "bpmn:DataInput",
  "bpmn:DataInputAssociation",
  "bpmn:DataObject",
  "bpmn:DataObjectReference",
  "bpmn:DataOutput",
  "bpmn:DataOutputAssociation",
  "bpmn:DataState",
  "bpmn:DataStore",
  "bpmn:DataStoreReference",
  "bpmn:Definitions",
  "bpmn:Documentation",
  "bpmn:EndEvent",
  "bpmn:EndPoint",
  "bpmn:Error",
  "bpmn:ErrorEventDefinition",
  "bpmn:Escalation",
  "bpmn:EscalationEventDefinition",
  "bpmn:EventBasedGateway",
  "bpmn:ExclusiveGateway",
  "bpmn:Expression",
  "bpmn:Extension",
  "bpmn:ExtensionAttributeDefinition",
  "bpmn:ExtensionDefinition",
  "bpmn:ExtensionElements",
  "bpmn:FormalExpression",
  "bpmn:GlobalBusinessRuleTask",
  "bpmn:GlobalChoreographyTask",
  "bpmn:GlobalConversation",
  "bpmn:GlobalManualTask",
  "bpmn:GlobalScriptTask",
  "bpmn:GlobalTask",
  "bpmn:GlobalUserTask",
  "bpmn:Group",
  "bpmn:HumanPerformer",
  "bpmn:ImplicitThrowEvent",
  "bpmn:Import",
  "bpmn:InclusiveGateway",
  "bpmn:InputOutputBinding",
  "bpmn:InputOutputSpecification",
  "bpmn:InputSet",
  "bpmn:Interface",
  "bpmn:IntermediateCatchEvent",
  "bpmn:IntermediateThrowEvent",
  "bpmn:ItemAwareElement",
  "bpmn:ItemDefinition",
  "bpmn:Lane",
  "bpmn:LaneSet",
  "bpmn:LinkEventDefinition",
  "bpmn:ManualTask",
  "bpmn:Message",
  "bpmn:MessageEventDefinition",
  "bpmn:MessageFlow",
  "bpmn:MessageFlowAssociation",
  "bpmn:Monitoring",
  "bpmn:MultiInstanceLoopCharacteristics",
  "bpmn:Operation",
  "bpmn:OutputSet",
  "bpmn:ParallelGateway",
  "bpmn:Participant",
  "bpmn:ParticipantAssociation",
  "bpmn:ParticipantMultiplicity",
  "bpmn:PartnerEntity",
  "bpmn:PartnerRole",
  "bpmn:Performer",
  "bpmn:PotentialOwner",
  "bpmn:Process",
  "bpmn:Property",
  "bpmn:ReceiveTask",
  "bpmn:Relationship",
  "bpmn:Rendering",
  "bpmn:Resource",
  "bpmn:ResourceAssignmentExpression",
  "bpmn:ResourceParameter",
  "bpmn:ResourceParameterBinding",
  "bpmn:ResourceRole",
  "bpmn:ScriptTask",
  "bpmn:SendTask",
  "bpmn:SequenceFlow",
  "bpmn:ServiceTask",
  "bpmn:Signal",
  "bpmn:SignalEventDefinition",
  "bpmn:StandardLoopCharacteristics",
  "bpmn:StartEvent",
  "bpmn:SubChoreography",
  "bpmn:SubConversation",
  "bpmn:SubProcess",
  "bpmn:Task",
  "bpmn:TerminateEventDefinition",
  "bpmn:TextAnnotation",
  "bpmn:TimerEventDefinition",
  "bpmn:Transaction",
  "bpmn:UserTask",
  "bpmndi:BPMNDiagram",
  "bpmndi:BPMNEdge",
  "bpmndi:BPMNLabel",
  "bpmndi:BPMNLabelStyle",
  "bpmndi:BPMNPlane",
  "bpmndi:BPMNShape",
  "dc:Boolean",
  "dc:Bounds",
  "dc:Font",
  "dc:Integer",
  "dc:Point",
  "dc:Real",
  "dc:String",
  "di:Extension",
  "zeebe:AdHoc",
  "zeebe:AssignmentDefinition",
  "zeebe:CalledDecision",
  "zeebe:CalledElement",
  "zeebe:ConditionalFilter",
  "zeebe:ExecutionListener",
  "zeebe:ExecutionListeners",
  "zeebe:FormDefinition",
  "zeebe:Header",
  "zeebe:Input",
  "zeebe:InputOutputParameter",
  "zeebe:IoMapping",
  "zeebe:JobPriorityDefinition",
  "zeebe:LinkedResource",
  "zeebe:LinkedResources",
  "zeebe:LoopCharacteristics",
  "zeebe:Output",
  "zeebe:PriorityDefinition",
  "zeebe:Properties",
  "zeebe:Property",
  "zeebe:Script",
  "zeebe:Subscription",
  "zeebe:TaskDefinition",
  "zeebe:TaskHeaders",
  "zeebe:TaskListener",
  "zeebe:TaskListeners",
  "zeebe:TaskSchedule",
  "zeebe:UserTask",
  "zeebe:UserTaskForm",
  "zeebe:VersionTag",
  "zeebe:ZeebeServiceTask",
] as const satisfies readonly SupportedElementType[];
